name: Deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      [main] 

  workflow_dispatch:

env:
  S3_BUCKET_NAME : walletplus
  CODE_DEPLOY_APPLICATION_NAME : walletplus 
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME : walletplus
 
jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      CI: false

    steps:
      - name: Deploy # Deploy to EC2
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /home/ubuntu/scan-front
            [ -e package-lock.json ] && rm package-lock.json
            [ -e yarn.lock ] && rm yarn.lock
            git pull origin main
            npm i
            npm run build
            cp build/* /var/www/html/plusscan.co -R
